### ISSUE TITLE
Not sure how to assist progress of migration for osx-arm64 while status is awaiting-parents (0)

### ISSUE THREAD

**Issue by nickpowersys** [conda-forge/airflow-feedstock#101]
### Comment:

I am not sure what the progress is of the migration, or if there is any dependency specific to airflow that is preventing it from appearing at [https://anaconda.org/conda-forge/airflow](https://anaconda.org/conda-forge/airflow). Thank you.

This PR was merged 2 days ago.
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4011/files

**Comment by nickpowersys** [comment]
See current status at https://conda-forge.org/status/#armosxaddition

**Comment by xylar** [comment]
It looks like the bot is waiting on:
https://github.com/conda-forge/python-ldap-feedstock/pull/22
https://github.com/conda-forge/leveldb-feedstock/pull/16
and a subsequent PR to:
https://github.com/conda-forge/plyvel-feedstock

Since those are bot related to extras, we can do a manual migration and just skip those extras for now for osx-arm64.  (Hopefully, I'll remember to check back when they no longer need to be skipped).  I don't think I'll have time to do that tonight.  Maybe tomorrow or over the weekend.

**Comment by xylar** [comment]
I got started but it's not going so well so far.  See #102

**Comment by xylar** [comment]
closed via #105 and #106

**Comment by nickpowersys** [comment]
@xylar Thank you very much, Xylar. I really appreciate it.

**Comment by xylar** [comment]
Sure, let me know how it goes.
