### ISSUE TITLE
No Python 3.7 builds from 2.4.3

### ISSUE THREAD

**Issue by sumanth-manchala** [conda-forge/airflow-feedstock#110]
Hi,

I'm curious about the deprecation of Python 3.7 in the Airflow conda package. I understand that the official Airflow project still supports Python 3.7+, but I'm wondering why the conda package doesn't.

Is there a specific reason why Python 3.7 was deprecated in the conda package? Is there a plan to support Python 3.7 until the official EOL?

**Comment by xylar** [comment]
@sumanth-manchala, conda-forge has stopped supporting python 3.7 more than 6 months ago.  We can only manage 4 versions at a time -- 3.8 to 3.11 in terms of the infrastructure for building packages and the human time of managing them.  We don't have any way to build Airflow with anything earlier than python 3.8 because the dependencies aren't available.

See https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7

**Comment by sumanth-manchala** [comment]
Thanks @xylar
