### ISSUE TITLE
Publish 1.10.14 in preparation for 2.0

### ISSUE THREAD

**Issue by tazimmerman** [conda-forge/airflow-feedstock#60]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

It's recommended that Airflow users upgrade to 1.10.14 before making the switch from 1.x to 2.x. If this work is already planned, please feel free to simply close this issue. Otherwise let me know if I can be of assistance.

**Comment by xylar** [comment]
Thanks for the heads up.  For whatever reason, the 1.10.14 release didn't trigger a PR.  Airflow is, by far, the most complicated feedstock I'm involved with so I'll do my best to take care of the 1.10.14 release in the next few days and see how the 2.0 and 2.0.1 releases go after that.

Thanks again for pointing this out.

**Comment by tazimmerman** [comment]
Thank you for the quick response!

Prior to submitting the issue, I had been attempting to build the package with `conda skeleton`, and let's just say I don't envy you. I very much appreciate you maintaining this package though. Despite it's complexities, Airflow is a great product.

**Comment by xylar** [comment]
So 2.0.0 and 2.0.1 are going to take a _massive_ amount of work.  There are 60 or so providers that I think are going to have to become conda-forge recipes and feedstocks (probably not separate outputs like now).  To make things more complicated, some of them have circular dependencies (they depend on airflow and airflow depends on them).  So that's going to be tricky.

So, long story short, don't expect 2.0.x anytime too soon but I'll work on it as I can.

**Comment by xylar** [comment]
Closing this because of #61.  We can open other issues to discuss 2.0.0 and 2.0.1 as needed.
